################################################################################
# Author     : Antony Onipko
# Copyright  : (c) 2016 Antony Onipko. All rights reserved.
################################################################################
# This work is licensed under the
# Creative Commons Attribution-ShareAlike 4.0 International License.
# To view a copy of this license, visit
# https://creativecommons.org/licenses/by-sa/4.0/
################################################################################
#
# Module manifest for the PowerShell OneDrive API wrapper 'PSOD'.
#
# Generated by: Antony Onipko
#
# Generated on: 30/06/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSOD.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'b9ca34f4-b90a-4e62-84ab-f40b4694837a'

# Author of this module
Author = 'Antony Onipko'

# Company or vendor of this module
# CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2016 Antony Onipko. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell wrapper for the OneDrive REST API.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
    'System.Web'
    'System.Windows.Forms'
)

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @(
    'PSOD.ps1xml'
)

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    'PSOD.format.ps1xml'
)

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @(
    'Copy-OneDriveItem'
    'Get-OneDriveAuthToken'
    'Get-OneDriveChildItem'
    'Get-OneDriveContent'
    'Get-OneDriveItem'
    'Invoke-OneDriveApiCall'
    'Move-OneDriveItem'
    'New-OneDriveFolder'
    'New-OneDriveToken'
    'Remove-OneDriveItem'
    'Set-OneDriveContent'
)

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = @(
    'PSOD'
)

# Aliases to export from this module
AliasesToExport = @(
    'odcopy'
    'odcp'
    'oddel'
    'odgc'
    'odgci'
    'odgi'
    'odls'
    'odmkdir'
    'odmove'
    'odmv'
    'odnf'
    'odnt'
    'odrm'
    'odsc'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://creativecommons.org/licenses/by-sa/4.0/'

        # A URL to the main website for this project.
        ProjectUri = 'https://gitlab.com/antonyoni/PSOD'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
